- name: Run docker image
  hosts: localhost

  tasks:
    - name: remove docker image
      command: docker image rm -f card-app:latest
      ignore_errors: yes

    - name: create docker image
      command: docker builb -t card-app .

    - name: deploy the container
      command: docker run -d -p 8082:80 --name payment-card-app card-app
